### ISSUE TITLE
JobTestConfig has a hardcoded relative path to gradle.properties

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#101]
I'm trying to use the AbstractJobTest under $PROJECT_DIR/examples/geonames/ but I'm getting an error because it cannot find the gradle.properties referenced by the relative path in JobTestConfig.

**Comment by sastafford** [comment]
We can assume that they will be using the ml-gradle plugin to test this stuff and will need a local gradle.properties.  Somehow need to have AbstractJobTest use BasicConfig instead of JobTestConfig.

**Comment by rjrudin** [comment]
I'm going to decouple AJT a bit from BasicConfig/BasicTestConfig as well. 

Note too that AJT doesn't do a ton yet. A developer could always write their own method for building the args that are passed into Main.

**Comment by sastafford** [comment]
Bug verified through #17
