### ISSUE TITLE
Reorganize job configuration into subprojects

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#107]
As a developer
I want to TITLE
So that I can maintain all job configuration as separate projects which are not coupled with other job configurations.  

Proposed Directory Structure.  The plan would be to replace the jobs projects with dependencies on the more common mature sub projects.  

-	core
-	app (has the Gradle file that produces the zip distribution; would depend on fixed versions of everything else, so it wouldn’t be part of the multi-project build)
-	jobs
  - documents
  - shapefiles
  - geonames
  - triples

**Comment by rjrudin** [comment]
Starting this up
