### ISSUE TITLE
Create EnhancedResourcesItemReader

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#110]
As a developer
I want to TITLE
So that I can have a reusable itemReader that accepts mlcp vars (i.e. inputFilePath) that can be used across any MSB job that reads data from the filesystem.

**Comment by sastafford** [comment]
I would say subclass this but the Resources[] var is private.  May just copy/paste/expand.  

https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/file/ResourcesItemReader.java

**Comment by sjiang99** [comment]
The reader needs to be able to support large number of resources, so loading them into an array, as in the implementation,  in a non-starter. We should modify this to only read a subset of the files at a time, whiling keeping the "current" pointer, and retrieve the next chunk after the current chunk is all returned in read().

**Comment by rjrudin** [comment]
The Resource itself is just a pointer. It doesn't hold any of the File data, you have to call getInputStream on it in order to get data. So I think an array of millions of Resource objects is fine.

**Comment by rjrudin** [comment]
Starting this

**Comment by rjrudin** [comment]
My approach for this is extending ResourceItemReader and adding support for mlcp-style inputs, such as input_file_path and input_file_pattern. Then I'm using PathMatchingResourcePatternResolver to construct a Resource[], which is then passed to the super class. I think this is the easiest way to leverage all of the goodness in the PMRPR class and ResourceItemReader as well.

**Comment by rjrudin** [comment]
Unfortunately PMRPR doesn't support regex's specified by input_file_pattern. So I'm overriding the read() method to apply the pattern check if a pattern has been set.
