### ISSUE TITLE
Move geonames code into a new jobs project

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#115]
The example project can exist, but it should depend on marklogic-spring-batch-geonames

**Comment by rjrudin** [comment]
Starting this

**Comment by sastafford** [comment]
Why couldn't it just depend on core?

**Comment by rjrudin** [comment]
My intent is to create a new "geonames" project under "jobs", and geonames will depend on core. The example project will then depend on marklogic-spring-batch-geonames. 

That way, the geonames config can be easily reused.
