### ISSUE TITLE
Set up Travis configuration files for CI

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#12]

**Comment by rjrudin** [comment]
Would love to learn how to do this in a secure way - i.e. install ml from scratch via sudo, run the tests, then uninstall ml.

**Comment by rjrudin** [comment]
@PaxtonHare Want to set this up again?

**Comment by rlouapre** [comment]
How about using Docker from Circle CI? The build can be tested a mulitple version of ML.
https://github.com/nativelogix/xquerrail2.framework/blob/master/circle.yml

**Comment by sastafford** [comment]
fba5753dc17000dfc2599dfc70d2b128338bc638
