### ISSUE TITLE
Cannot execute jobs.bat on Windows because classpath exceeds character limit

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#123]
e:\temp\jobs-DEV\jobs-DEV\bin>jobs.bat --list-config
The input line is too long.
The syntax of the command is incorrect.

**Comment by sastafford** [comment]
The jobs.zip file was 71 MB.  Need to shrink it down if possible.

**Comment by rjrudin** [comment]
What if the jobs application used the Gradle wrapper to download the dependencies it needed? And the shell script was instead a way to invoke the Gradle wrapper?

Then the application zip would be extremely small. The Gradle wrapper would be in it, which would download Gradle and any other dependencies needed. 

I think we can still use the application plugin, or maybe we're better off putting our own script together.

**Comment by sastafford** [comment]
I'd prefer to use the distribution plugin if possible cause its turn key.  We really need a user friendly solution here.  I'm picturing a settings file where we would reference every JobConfig that you would want 'jobs' to run.  Then auto-magically everything just works.  I'm open for any solution.  I'm going to break out the file-importers into several subprojects since that is the main culprit right now.

**Comment by rjrudin** [comment]
Here's a separate approach - making an executable jar with the classpath in its manifest - https://discuss.gradle.org/t/problem-with-running-application-classpath-too-big/7600/10

**Comment by rjrudin** [comment]
I also wonder how important this is. I'm on Windows, and I use git bash as a terminal - I think it's very rare that someone would still use the DOS prompt as a terminal, as it's so limited. The jobs program runs fine via git bash, but not via the DOS prompt. I feel a legitimate approach is for someone wanting to use this in Windows, they need to run it via something besides a DOS prompt, which in general is a good idea for running anything on Windows.

**Comment by sastafford** [comment]
I'll merge this one once #110 is complete.

**Comment by sastafford** [comment]
e9206a7685d338b06462ade48ce24ca693ae9123
