### ISSUE TITLE
Filter out non JobConfiguration files when running ./jobs --list

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#126]
When I run the exe with the --list parameter, I get the JobConfiguration information.  That is good.  But we would like to filter out the non JobConfiguration files.  

The JobConfig for this exe has been highlighted.  

e:\temp>jobs-DEV\jobs-DEV\bin\jobs.bat --list
Listing Spring Configuration classes:
com.marklogic.spring.batch.core.repository.dao.MarkLogicDaoConfig
com.marklogic.spring.batch.MainConfig
**_com.marklogic.spring.batch.config.ImportDocumentsFromDirectoryConfig
com.marklogic.spring.batch.geonames.IngestGeonamesToMarkLogicConfig_**
org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration
org.springframework.batch.core.configuration.annotation.ScopeConfiguration
org.springframework.batch.core.configuration.annotation.ModularBatchConfiguration
com.marklogic.client.spring.BasicConfig
org.springframework.retry.annotation.RetryConfiguration
org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration
org.springframework.cache.annotation.ProxyCachingConfiguration
org.springframework.context.annotation.MBeanExportConfiguration
org.springframework.context.annotation.LoadTimeWeavingConfiguration
org.springframework.scheduling.annotation.SchedulingConfiguration
org.springframework.scheduling.annotation.ProxyAsyncConfiguration

**Comment by rjrudin** [comment]
What should the filter be? I considered only finding subclasses of AbstractMarkLogicBatchConfig, but I feel that's too restrictive, because it's not a requirement that a config class be a subclass of that. 

I'm not sure there's any other filter that can be safely applied other than classes with the Configuration annotation. I think this is a case where we can be fine with "false positives" as opposed to a filter that has a chance of omitting a job configuration class.

**Comment by sastafford** [comment]
I would start off by filtering out org.springframework.*.  That gets rid of the majority of the configs.  

After that there are 3 config classes under com.marklogic.* that should just be filtered out via their full name. 
 * com.marklogic.spring.batch.core.repository.dao.MarkLogicDaoConfig
 * com.marklogic.spring.batch.MainConfig
 * com.marklogic.client.spring.BasicConfig
