### ISSUE TITLE
Make it easier for external programs to run a job

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#130]
Paxton ran into a bunch of issues when integrating and running a Spring Batch job from the Data hub project.  Most of the autowiring configuration is behind the scenes and taken care of through the ml-java-client-util library.  But for Data Hub it provides much of the ML Property configuration (host, port, etc).  We need to make it easier for external programs to pass in their configuration.  

Comments from @paxtonhare

MarkLogicDaoConfig
@ Import relies on BasicConfig - would want to allow external program to inject own set of properties from other objects.  

AdaptedStepExecution -  If your job throws an exception that does not get caught, the following code bombs a program.  Cannot go generic with throwable.  this is causing xml serialization headaches, fix is to comment out, 

public List<Throwable> getFailureExceptions() {
	return failureExceptions;
	}

**Comment by paxtonhare** [comment]
Another one:

I needed access to the ConfigurableApplicationContext that gets constructed in Main.java because I needed to inject a concrete instance of a class as a bean like so:

```java
ctx.getBeanFactory().registerSingleton("flow", flow());
```

Because of this I couldn't just call the Main class with some args. I had to duplicate much of what it does in one of my own classes.

**Comment by rjrudin** [comment]
Could you subclass Main? I put most of the code in protected methods so it's easy to subclass Main and override what you need to.

**Comment by paxtonhare** [comment]
@rjrudin I didn't try subclassing. Something felt gross about subclassing a Main class :)

But I also didn't need all the fancy OptionsParsing and whatnot. I was able to simplify it significantly just by building up the params I needed.

**Comment by paxtonhare** [comment]
@sastafford I'd like to depend on your core lib from the Data Hub. But in order for me to use it I need that getFailureExceptions() commented out or removed.

Shall I make a PR? or is there another approach that we can try other than commenting/removing?

**Comment by sastafford** [comment]
@paxtonhare, you are going to probably need to make some changes to the DataHub framework with the upcoming release of MarkLogic Spring Batch.  I went ahead and deleted MarkLogicDaoConfig and made it easier to configure the MarkLogicJobRepository.  Let me know what you think.
