### ISSUE TITLE
Example rdbms_1 does not build due to missing sql-job jar

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#145]
From Venu:

I checked out the dev branch and trying to build sample example and it cannot find com.marklogic:marklogic-spring-batch-sql:0.5.2
Is this published or how can I use my local version?

What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find com.marklogic:marklogic-spring-batch-sql:0.5.2.
  Searched in the following locations:
      https://jcenter.bintray.com/com/marklogic/marklogic-spring-batch-sql/0.5.2/marklogic-spring-batch-sql-0.5.2.pom
      https://jcenter.bintray.com/com/marklogic/marklogic-spring-batch-sql/0.5.2/marklogic-spring-batch-sql-0.5.2.jar
      file:/C:/Users/viyengar/.m2/repository/com/marklogic/marklogic-spring-batch-sql/0.5.2/marklogic-spring-batch-sql-0.5.2.pom
      file:/C:/Users/viyengar/.m2/repository/com/marklogic/marklogic-spring-batch-sql/0.5.2/marklogic-spring-batch-sql-0.5.2.jar
  Required by:
      :invoices:unspecified

**Comment by sastafford** [comment]
To move past this issue, run the following gradle command from your project root directory.  

     gradle publishToMavenLocal

This command will publish all the job jars to your local maven repository and you will pick up the indicated jar below.  Sorry I did not catch this.  I’ll update the documentation for this one.

**Comment by venuiyengar** [comment]
I still have the same issue, am I missing something?

**Comment by sastafford** [comment]
Verified fix
