### ISSUE TITLE
As a developer I want to use DMSDK - EA3 version So that I can update DMSDK example code

### ISSUE THREAD

**Issue by venuiyengar** [sastafford/marklogic-spring-batch#153]

**Comment by sastafford** [comment]
Do it

**Comment by venuiyengar** [comment]
After loading the docs as part of this test - loadXmlDocumentsTest; Where is the code to remove the loaded docs. When I check the qconsole; the docs are removed. I can not seem to find code where/how the documents are removed in AbstractJobTest;  I want to write another example that uses StructuredQueryBuilder and add a test for that.

**Comment by venuiyengar** [comment]
It looks like loadXmlDocumentsTest is being ignored when I do gradle test. Any idea why this is the case?

**Comment by sastafford** [comment]
Done
