### ISSUE TITLE
Create an example project that ingests geonames

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#17]

**Comment by sastafford** [comment]
As a user
I want to TITLE
So that I can have a reusable job to ingest Geonames into MarkLogic

**Comment by rjrudin** [comment]
I think this should be a sample project - tossing into 0.4.0 so that it can be reworked into a sample project. I don't think geonames is generic enough to warrant including it the jobs library, but showing a sample project would be valuable for anyone wanting to work with geonames data.
