### ISSUE TITLE
Minor typo in readme

### ISSUE THREAD

**Issue by jgraham0325** [sastafford/marklogic-spring-batch#176]
Hey,

Project looks great! Just spotted a minor typo in the root folder README

 testComp**l**ile "com.marklogic:marklogic-spring-batch-test:0.7.0"

Should read:
 testCompile "com.marklogic:marklogic-spring-batch-test:0.7.0"

Slightly sneaky one to spot when copying and pasting into a new project.

Thanks,
James

**Comment by sastafford** [comment]
Thanks for the catch and giving me a heads up.
