### ISSUE TITLE
Can't clone repo, even with git-lfs installed

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#184]
Tried to clone repo, ran into issue requiring git-lfs. Installed git-lfs, installed it, then got this error:

$ git lfs install
Git LFS initialized.

$ git clone https://github.com/sastafford/marklogic-spring-batch.git
Cloning into 'marklogic-spring-batch'...
remote: Counting objects: 12563, done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 12563 (delta 85), reused 0 (delta 0), pack-reused 12195
Receiving objects: 100% (12563/12563), 42.70 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (4459/4459), done.
fatal: examples/entityEnrichment/srcUnknown command ""
/main/resources/nlp/en/en-ner-date.bin: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by sastafford** [comment]
I am using git lfs due to the entity enrichment sample.  It's been a bit problematic with that dependency.   I think it would be simpler to put the Entity Enrichment into its own github project (like rowToDoc) and deprecate any use of git lfs.

**Comment by sastafford** [comment]
I've taken out the dependency of git lfs since I've removed the files that used git lfs.  Should be good now.
