### ISSUE TITLE
JobProjectTestConfig depends on undefined job.home property

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#185]
I ran into this while trying to use msb 0.7.4 and when trying to run the latest tests for rowToDoc. AbstractJobTest depends on JobProjectTestConfig, which has the following annotations on it:

@PropertySource(value = "classpath:job.properties", ignoreResourceNotFound = true)
@PropertySource(value = "file:${job.home}/job.properties")

The first one makes sense, but I'm not sure what the right way is to define the second one. The only way the second one works is if "job.home" is defined somewhere - such as by the optional job.properties file in the first annotation. 

For rowToDoc, I was able to get the tests passing by duplicating the contents of gradle.properties into src/test/resources/job.properties and changing the property names like so:

job.home=./src/test/resources
mlAppName=rowToDoc
marklogic.host=localhost
marklogic.port=8155
marklogic.username=admin
marklogic.password=admin

Ideally, I'd like to default to using what's in gradle.properties (I'm trying to make an app that uses AbstractJobTest). But JobProjectTestConfig shouldn't force me to define a file, which the 2nd annotation is doing, and that's complicated by the fact that it requires a property to resolve its path.

**Comment by sastafford** [comment]
I realized that this a job.home variable definition was a mistake during my journey to CI testing.  

On the dev branch for [JobProjectTestConfig](https://github.com/sastafford/marklogic-spring-batch/blob/dev/test/src/main/java/com/marklogic/spring/batch/test/JobProjectTestConfig.java) I've taken out that requirement.  It expects job.properties in the classpath or in the same directory.  

The reason I had this was to avoid defining a properties file for every example.  I'm actually experimenting with running the examples under a new samples directory and combining all tests in that directory.  The use case I'm trying to satisfy is a batch operator that needs to run multiple defined jobs in the same code base.

**Comment by rjrudin** [comment]
I think the idea behind job.properties makes sense, I just wouldn't put it in the truly reusable parts of msb-test. Though perhaps keeping it optional suffices too.

The import of SpringDatabaseClientConfig forces a client to use marklogic.host/port/username/password too. But in my case, it's simpler to just use BasicConfig/BasicTestConfig to read from gradle.properties by default so I don't have to duplicate any property values in multiple files. So I don't think JobProjectTestConfig should import SDCC - that should be a convenience that's up to the client.
