### ISSUE TITLE
Add ml-migration-starter artifacts

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#186]
Every class in the com.marklogic.spring.batch package in https://github.com/rjrudin/ml-migration-starter can be contributed back to MSB.

Note that the ColumnMapSerializer in MMS were copied from rowToDoc. I think those 3 classes are worth adding to MSB, as they're simple and generic, and I think ColumnMap is useful in a lot of contexts besides rowToDoc.

**Comment by sastafford** [comment]
482b9a0b8464b6a599ec5f5b5a7c5e929cdf38e7
