### ISSUE TITLE
Read all rows from all tables

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#203]
This seems like a useful component to have - a Reader that, on open, queries for all tables, and then constructs a JDBC reader for each one with a query of "SELECT * from (table name)". And it uses a ColumnMapRowMapper for each reader (though that could be a property of the Reader so it could be overridden).

That gives folks an OOTB way with ml-migration-starter to do a full dump of all tables into ML.

**Comment by sastafford** [comment]
I've actually given some thought to querying the system tables to read in each table AS-IS.  Would reading from the system tables of a database be configurable via the JDBC driver?

**Comment by rjrudin** [comment]
This is the basic code for getting all the table names:

new JdbcTemplate(dataSource).execute(new ConnectionCallback<List<String>>() {
			@Override
			public List<String> doInConnection(Connection con) throws SQLException, DataAccessException {
				ResultSet rs = con.getMetaData().getTables(null, null, "%", null);
				List<String> list = new ArrayList<>();
				while (rs.next()) {
					list.add(rs.getString("TABLE_NAME"));
				}
				return list;
			}
		});

**Comment by sastafford** [comment]
So this has been created in the ml-migration project (AllTablesItemReader).  Do we bring that class into this project?

**Comment by rjrudin** [comment]
Yes
