### ISSUE TITLE
ColumnMapProcessor creates handle without format, XCC adapter sending incorrect format as well

### ISSUE THREAD

**Issue by malteseduck** [sastafford/marklogic-spring-batch#207]
https://github.com/sastafford/marklogic-spring-batch/blob/master/infrastructure/src/main/java/com/marklogic/spring/batch/item/processor/ColumnMapProcessor.java#L38

When it creates the StringHandle it doesn't use getFormat() to see if any format has been specified and use that in the handle, so it comes back as type UNKNOWN.  If there is a format it should use it.

It could also determine format based on the specified serializer as well, perhaps.

This would lead to a problem in the DefaultDocumentWriteOperationAdapter.adaptMetadata() when trying to save JSON data.  It seems it would, but the adaptMetadata() pulls the format off the metadata object instead of the content object, so if you are trying to save JSON it says the type is XML instead, which gives a "XDMP-DOCROOTTEXT: Invalid root text" error.  The ContentCreateOptions should use the content handle to get the format, and that format should probably be "correct" to avoid any server errors.

Am I seeing this correctly, or missing something somewhere?

**Comment by sastafford** [comment]
I'm sorry that I missed your issue coming across email.  I would have replied sooner.  

_It could also determine format based on the specified serializer as well, perhaps._

I understand what you are seeing now that I'm reviewing some other jobs that utilize the ColumnMapProcessor.  Take a look at this [import delimited file] job(https://github.com/sastafford/hector/blob/master/src/main/java/com/marklogic/hector/ImportDelimitedFileJob.java).  As you mentioned, I'm setting the format via the specified serializer. I also have this [TempRestBatchWriter](https://github.com/sastafford/marklogic-spring-batch/blob/master/infrastructure/src/main/java/com/marklogic/spring/batch/item/writer/support/TempRestBatchWriter.java) that I also set the Format in there.  So I'm kind of setting it twice which probably isn't necessary.  

The reason TempRestBatchWriter exists is that the ml-javaclient-util is till on the Java Client API 3.5 which does not support that setFormat() function.  

This is what I can do.  I can set the format of the StringHandle in the ColumnMapProcessor as a default.  I think that should address what you are seeing.  What do you think?

**Comment by malteseduck** [comment]
That would probably fix the issue with the ColumnMapProcessor.  The metadata adapter still is setting the format of the write operation to the format of the metadata, not the content itself, so it only works for XML content.  To get around it I created a "quick and dirty" implementation that just overrode the "adapt" method:

`public class XccDocumentWriteOperationAdapter extends DefaultDocumentWriteOperationAdapter {

    @Override
    public Content adapt(DocumentWriteOperation operation) {
        Content content = super.adapt(operation);
        ContentCreateOptions options = content.getCreateOptions();

        // Quick fix to allow the content format to be set correctly from the content instead of from the metadata
        Format format = ((StringHandle) operation.getContent()).getFormat();

        if (Format.JSON.equals(format)) {
            options.setFormat(DocumentFormat.JSON);
        } else if (Format.XML.equals(format)) {
            options.setFormat(DocumentFormat.XML);
        }

        return content;
    }
}`

Maybe not a good global solution but it worked for my case.

**Comment by sastafford** [comment]
Is your issue that the properties fragment always defaults to XML even if the content is json?

**Comment by malteseduck** [comment]
I am really sorry, the other problem is in another project:

https://github.com/sastafford/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/xcc/DefaultDocumentWriteOperationAdapter.java#L69

I apparently got a little mixed up, it is in the adapter the XccBatchWriter is using, but you are using the RestBatchWriter.  Sorry about that.
