### ISSUE TITLE
Rename the jar file to publish to bintray - marklogic-spring-batch

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#27]
I like the name marklogic-spring-batch.  "data-migration" for a package name is too narrow in scope for the general category of batch processing.

**Comment by rjrudin** [comment]
Agree, I'll rename it. 

We can always have multiple published jars too, with different ones using different configurations. That way, if I just need some software for disk-based data loading, I don't grab a jar that brings a ton of JDBC dependencies.
