### ISSUE TITLE
Refactor Corb Job to utilize more Spring Batch features

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#30]
There are some features in Spring Batch that we can utilize to make this even better and extensible.

**Comment by rjrudin** [comment]
Whatcha got in mind?

**Comment by sastafford** [comment]
1) I found this Abstract class that can eliminate one of the custom abstract classes

c4579b90a6270cf6a400fde8647e2adab6d745be

2) I think we can make the CorbReader more generic and make it into a MarkLogicItemReader.  The parameter would be a module file path and it would return a string, document, binary, etc.  It doesn't care.  

f3fef25a71ecbc23e102411b6442ecf217d7d1b4

3) I spent some time trying to write unit tests for this MarkLogicItemReader but I ran into some issues just running a single step.  I created the following LoggingItemWriter to help facilitate that testing. 

0857ae2021607f7b9aaa1e1ac3fcdb2676e2b911
