### ISSUE TITLE
Create command line MSB application launcher

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#31]
As a user
I want to TITLE
So that I can launch a Spring Batch job from the command line

Initially let's support a unix only command line utility.  The name of the script should be **msb.sh**

The first accepted parameter would be the name of the job.  This would load the appropriate job spring configuration and run the specified job with parameters.

Here are a couple of examples
`msb -job corb -username admin -password admin -host localhost -port 8100 -uris /ext/uris.xqy -transform /ext/transform.xqy`

`msb -job loadFiles ... -input_file_path /tmp/`

**Comment by rjrudin** [comment]
How about two inputs - the path to a Spring XML file and the name of a job (a Spring bean) to launch?

The Spring XML file provides a nice way of specifying the config of Spring Batch. It could override default beans in MSB.

**Comment by sastafford** [comment]
Why would I need two inputs?  I'm assuming Java config for all the Spring config. I'd rather to keep it to one parameter.

**Comment by rjrudin** [comment]
That requires MSB to know of every job possible to be invoked. I think MSB should be less in the business of defining jobs and steps vice defining reusable readers/processors/writers, the ML job repository, etc. 

Then, as an MSB user, I want to reuse all those components to help me define my custom jobs/steps. I can define those in an XML file - thus requiring no coding in an IDE - and feed them into the MSB command line interface, along with the name of the job (the name could be optional - if there's only one job defined, MSB can default to running that).
