### ISSUE TITLE
Use ml-gradle to stand up test app

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#4]
I noticed the config defaults to faa/8100. Would be nice to have a simple ml-gradle setup to stand up a basic REST API server with the corb modules loaded.

**Comment by sastafford** [comment]
I have a ml-gradle config setup, trying to set up the appropriate permissions.  But I think this is a MarkLogic application that would operate on a different ML application.  So there needs to be config for both the Spring Batch ML app and then the other application.

**Comment by sastafford** [comment]
@rjrudin, do you agree we can close this issue?  We have the sample spring-batch application that is used by the test cases.
