### ISSUE TITLE
Ingest RDBMS data into MarkLogic via Hibernate

### ISSUE THREAD

**Issue by mpheckel** [sastafford/marklogic-spring-batch#44]
Given the familiarity most Java developers have with Hibernate it's likely that they would feel more comfortable using it as part of a MarkLogic data import strategy.  If feasible, it's likely there would be a trade off in the form of ease of use for operational efficiency.  However, it's also likely that in certain situations this would be acceptable.

This issue serves as a marker for investigating Hibernate's feasibility as part of a MarkLogic data import strategy with ml-spring-batch.

**Comment by sastafford** [comment]
Matt - there is some [out of the box support](http://docs.spring.io/spring-batch/trunk/reference/html/readersAndWriters.html#HibernateCursorItemReader) for Hibernate that can be utilized.  Check out Spring's EmbeddedDatabase capability and how Rob used it on one of his tests.  

https://github.com/sastafford/marklogic-spring-batch/blob/master/src/test/java/com/marklogic/spring/batch/sql/ReadAndWriteColumnMapsTest.java

**Comment by sastafford** [comment]
As a developer
I want TITLE
So that I can have an example job of how Hibernate could be used to extract data from a RDBMS and load the data into MarkLogic

**Comment by sastafford** [comment]
It was concluded that due to mismatching libraries between Hibernate and Spring Batch that it was not possible at this time to achieve this issue.
