### ISSUE TITLE
Load triples

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#48]
As a developer
I want to TITLE
So that I can create a Spring Batch job that will read in triples and ingest the data into MarkLogic

Given a single file containing triples in Turtle format
When the job is executed with the following parameters
 * input_file_path = directory that contains the file
 * input_file_type = rdf
Then the triples are ingested into MarkLogic

Guidance
- Assume the triples are in turtle format in a single text file
- Don't worry about performance at this point, just get the data in and ingested
- No-op your ItemProcessor, no need to transform

This is a project that might provide some assistance.
https://github.com/marklogic/marklogic-jena

You may need to create a different type of ItemWriter.

**Comment by sastafford** [comment]
From: Venu
In order to run the migrator, I believe it needs bunch of stuff defined as part of options. How does it read the options. IS there a sample application.propeties file?
SAS: Take a look at this [test class[](https://github.com/sastafford/marklogic-spring-batch/blob/dev/src/test/java/com/marklogic/spring/batch/job/LoadDocumentsFromDirectoryJobTest.java) as an example of how to pass in properties.  Assume that properties will be passed in via a job.properties file or command line arguments. 

I am working on RDFTripleItemReader.  By the way how do you test itemReaders and itemWriters? I do not see any unit tests for those.
SAS: I should have a test class for the DocumentItemWriter.  I'll create an issue for that one.  In all other cases, we are using existing ItemReaders from Spring Batch or an anonymous class in the case for some ItemProcessors.

**Comment by venuiyengar** [comment]
I am learning RDF and Jena as that will the core library that I need for RDFTriple import. I have the RdfTripleItemReader sort of working. I need to add jena jars to the build.gradle and also there has been some changes to the jars with the new version that I am hashing out.

**Comment by venuiyengar** [comment]
I created a branch load_triples and did git checkout load_triples
When I do git pull origin load_triples - It says
fatal: Couldn't find remote ref load_triples
Can you tell me why I can not pull origin to this branch?

**Comment by venuiyengar** [comment]
I have committed my changes to load_triples branch

**Comment by sanjuthomas** [comment]
@venuiyengar 

One testcaes failed in the dev branch that I checkout out to work on another story. Just thought to notify you.

20:55:58.550 [Test worker] INFO  c.m.s.b.item.AbstractDocumentWriter - writing triple records
20:55:58.759 [Test worker] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing step testStep in job testJob
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at /graphs/sparql: Internal Server Error. Server Message: XDMP-TRPLIDXNOTFOUND: xdmp:security-assert("http://marklogic.com/xdmp/privileges/rest-reader", "execute"), let $rule := conf:get-sparql-protocol-rule() let $params := rest:process-request($rule) let $headers := eput:get-request-headers() let $method := eput:get-request-method($headers) let $env := map:map() let $params := local:validate-params($rule, $env, $params) let $body := switch ($method) case "GET" return text { fn:head((map:get($params, "query"), map:get($params, "update"))) } case "POST" return xdmp:get-request-body(eput:get-content-format($headers, $params))/node() default return fn:error((), "REST-UNSUPPORTEDMETHOD", $method) let $result := semmod:sparql-query($headers, $params, $body) let $response := semmod:results-payload($headers, $params, $result, local:sparql-callback#2) return if ($response instance of node() and $response/self::semmod:malformed-query) then (xdmp:set-response-code(400, "Malformed Query"), $response) else $response -- Triple index not enabled . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4626) ~[java-client-api-4.0-SNAPSHOT.jar:na]


java.lang.AssertionError: expected:<COMPLETED> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.marklogic.spring.batch.AbstractSpringBatchTest.launchJobWithStep(AbstractSpringBatchTest.java:80)
	at com.marklogic.spring.batch.rdf.ReadAndWriteTripleTest.readAndWriteTriples(ReadAndWriteTripleTest.java:54)
	at com.marklogic.spring.batch.rdf.ReadAndWriteTripleTest.writeTriples(ReadAndWriteTripleTest.java:44)

**Comment by venuiyengar** [comment]
Make sure you do gradlew mlDeploy so that it creates the triple index.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by sanjuthomas** [comment]
@venuiyengar  thanks, that helped.

**Comment by sastafford** [comment]
Closing this issue.  Initial scope done.  Follow on work in #68
