### ISSUE TITLE
Load ML config and modules from test directory

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#55]
As an MSB user
I want to TITLE
So that it's clear that the ml-config and ml-modules are used for testing and are not part of the distributable library

- ml-config can be moved to src/test/ml-config - just set "mlConfigDir" to "src/test/ml-config" in gradle.properties
- ml-modules can be moved to src/test/ml-modules. To tell ml-gradle to find modules there, just add the following to build.gradle (I'm adding a ticket to ml-app-deployer to allow this to be defined via a property):

    ext { mlAppConfig { modulePaths = ["src/test/ml-modules"] } }

**Comment by sastafford** [comment]
Thanks for the tip for setting the modules path.  But I do have a need for content within ml-config and ml-modules to be part of the distribution library.  

To support a MarkLogic Job Repository I need to add range indices, support a search options file, and have some access control set.  Yes, some of the test modules should not be included in the distribution.  

So this works...

ext {
  mlAppConfig {
      modulePaths = ["src/main/ml-modules", "src/test/ml-modules"]
  }
}

But now I have to package some ML config in my distribution OR I could deploy via ml-app-deployer which could be an option.

**Comment by sastafford** [comment]
Closed.  I wrote Issue #63 as an action item from this issue
