### ISSUE TITLE
Simplify ml-config for testing

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#56]
I recommend just using admin/admin for everything for deploying the test application and running the tests. You can use other users to verify certain things in a test, but otherwise, I don't think there's any harm in using admin for deploying the app and being the default user for tests. 

So "simplify" means:

1. In gradle.properties, only define mlUsername and mlPassword. Let the admin user take care of everything - using the Manage API and using the REST API to load modules. 
1. Drop every role/user except for ones that are used for specific tests - i.e. to verify that a certain capability in marklogic-spring-batch requires a certain role/privilege. 
1. I'd drop rest-api.json, it's only needed if you need to override something in it. Otherwise, ml-gradle will generate a vanilla one for you on the fly.
1. Do you need the protected-collection - is it a requirement that marklogic-spring-batch depends on a protected-collection?

**Comment by sastafford** [comment]
@rjrudin I believe this issue may now be OBE.  The Jobs rely on the JobProperties for running a job.  This is now defaulting to admin/admin.  But the other credentials are for the MarkLogic Job Repository.  These roles and users are locked down on purpose.
