### ISSUE TITLE
Import JSON Documents from Directory

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#57]
As a user
I want to TITLE
So that I can quickly ingest JSON documents and begin to query over the data

Given three JSON documents in a directory

When 
 * document_type = json
 * input_file_path = the directory containing the three json docs
 * input_file_path = a value which would exclude out 1 of the 3 json documents

Then two of the three documents exist in MarkLogic after the job concludes

**Comment by sastafford** [comment]
1.	Do we have to ingest JSON documents via a REST end point or there is different protocol that you would like to use to talk to ML?
_You are going to modify the [LoadDocumentsFromDirectoryJob](https://github.com/sastafford/marklogic-spring-batch/blob/dev/src/main/java/com/marklogic/spring/batch/job/LoadDocumentsFromDirectoryJob.java) to import JSON files.  You are going to use the same ItemReader but a different ItemProcessor and ItemWriter.  You will need to create a new ItemWriter similar to the [DocumentItemWriter](https://github.com/sastafford/marklogic-spring-batch/blob/dev/src/main/java/com/marklogic/spring/batch/item/DocumentItemWriter.java).  _

2.	Is this about just picking a JSON and storing it as it is? 
_Yes_

3.	Do we have to support document URI generation?
_No.  That will be my job when I complete issue #60.  For now, use the URI_ID parameter.

4.	Do we have to support the URI pattern? (controlled by the user by config) like prefix all document URIs with /xyz/abc/
_Out of scope for this issue, but that is something that we need to support.  I might be able to address via Issue #60._

5.	Do we have to support storing the property fragment along with document? (collection, privileges) 
_No, we can add later_

6.	Do we have  to ingest line delimited json as separate documents? 
_No, that is out of scope for this issue_

7.	Do we have to ingest array elements (if in the root) as separate documents?
_No, that is out of scope for this issue_

8.	Do we have  any kind of logging/stat requirements? Like how we report back the status of the job and number of documents created?
_No, that is one of the features of Spring Batch.  Batch Job status, number of docs processed are provided by the Spring Batch framework._
 
9.	Do we have  to support any kind validation? Like a json schema validation.
_Throw an exception if the JSON is malformed)

10.	Do we have any kind of resource/performance specification? Like don’t load the entire JSON into memory but stream that out to save some RAM.
_Get it working first.  We will open up another issue later if performance is an issue_

11.	Whats the definition of done other than code completion and functionality completion? 
1.	Unit test coverage % ?
2.	Integration test ?
3.	Java API Documentation?

_I would like to see an integration test like [LoadDocumentsFromDirectoryTest](https://github.com/sastafford/marklogic-spring-batch/blob/dev/src/test/java/com/marklogic/spring/batch/job/LoadDocumentsFromDirectoryJobTest.java)._

**Comment by sanjuthomas** [comment]
about the acceptance criteria - 

" input_file_path = the directory containing the three json docs
input_file_path = a value which would exclude out 1 of the 3 json documents "

the second key is input_file_path or input_file_pattern?

**Comment by sanjuthomas** [comment]
Do we have a any standard code formatter xml file for eclipse? PMD or Findbug rules?

**Comment by rjrudin** [comment]
I recommend .editorconfig - here's a simple one - https://github.com/rjrudin/slush-marklogic-spring-boot/blob/dev/templates/.editorconfig

I know Eclipse has a plugin for it. But it's already integrated with Intellij.

**Comment by sanjuthomas** [comment]
@rjrudin , do you know why the tests are failing when ran stand alone (independently) from IDE?

![image](https://cloud.githubusercontent.com/assets/949540/15458196/f494e330-2064-11e6-99b1-034fc36c885c.png)

**Comment by sanjuthomas** [comment]
@rjrudin  Thanks; I can use Intellij. 

Do you know why many test cases are failing on standalone mode? (when ran independently from IDE?)

![image](https://cloud.githubusercontent.com/assets/949540/15458449/34f6ac4e-2068-11e6-884a-10ebbf07f992.png)

**Comment by sastafford** [comment]
I am using a updated version of the Java Client API that has a bug fix.  It should have a priority over the older java client api jar in the classpath.  

https://github.com/sastafford/marklogic-spring-batch/wiki/Troubleshooting

**Comment by sanjuthomas** [comment]
@sastafford  Please see the pull request - https://github.com/sastafford/marklogic-spring-batch/pull/62

**Comment by sanjuthomas** [comment]
@sastafford new pull request is at https://github.com/sastafford/marklogic-spring-batch/pull/64
