### ISSUE TITLE
Creating Documents from Delimited Text Files

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#58]
As a developer
I want to TITLE
So that I can quickly ingest delimited text files into MarkLogic

The job should accept all the [input parameters](http://docs.marklogic.com/guide/mlcp/import#id_70366) that mlcp expects.  

**Constraints**
- Reuse the [FlatFileItemReader](http://docs.spring.io/spring-batch/trunk/reference/html/readersAndWriters.html#flatFileItemReader)
- Any transforms should occur in the ItemProcessor.

**Comment by sanjuthomas** [comment]
@sastafford  is this a new job or an enhancement on LoadDocumentsFromDirectoryJob?

**Comment by sastafford** [comment]
New job

 
 
  On Fri, May 27, 2016 at 11:48 PM, Sanju Thomas<notifications@github.com> wrote:   
@sastafford is this a new job or an enhancement on LoadDocumentsFromDirectoryJob?

**Comment by sanjuthomas** [comment]
@sastafford I have gone thru the MLCP options, a question that I thought to ask (I haven't tested yet, if you know it already I can save sometime) is, does MLCP support array datatype while ingesting delimited text file? 

For example the children in the below given JSON. If it supports, how would it separate the array elements from other properties?
{
"id" : 1 [number]
"name" : "Doe, John" [string]
"children" : [ {
   "id" : 10 [number]
   "name" : "First Child" [string]
}

On the side note, I am thinking about using https://github.com/FasterXML/jackson-dataformat-csv for csv JSON ingestion and datatype support.

**Comment by sastafford** [comment]
MLCP does not support an array datatype for a single column.  MLCP will take the column header and use for the element name but will not break up a cell into an array.  

For this task, I want you to do the same thing that mlcp does.  This will serve as a base job template for any one parsing delimited files.  If someone wants to translate one column into an array then they will use your job as the starting point.  

This is one of the advantages of Spring Batch vs MLCP is the ability to quickly (via the ItemProcessor) change the transform.  MLCP does not provide this type of modification without a lot of work.

**Comment by jmakeig** [comment]
mlcp uses an open-source library to do CSV parsing, if I recall correctly. You might want to start there.

**Comment by sastafford** [comment]
This job has been moved into its own [project](https://github.com/sastafford/hector)
