### ISSUE TITLE
Pass the database client parameters via the command line or properties file

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#61]
Host, password, username, and password should be accepted as input parameters for the job

**Comment by sastafford** [comment]
http://www.petrikainulainen.net/programming/spring-framework/spring-from-the-trenches-injecting-property-values-into-configuration-beans/

Use the DatabaseClientConfig in the ml-java-client-uti

**Comment by rjrudin** [comment]
How would this work? Would a Reader or Writer expect to find those parameters and then construct a DatabaseClient?

I recommend having e.g a Writer depend on a DatabaseClient, typically via its constructor. Whomever is responsible for instantiating the Writer then must fulfill the DatabaseClient dependency.

**Comment by sastafford** [comment]
As a developer wanting to run a MSB job
I want to TITLE
So that I can specify where the ItemWriter writes the documents.

**Comment by sastafford** [comment]
@rjrudin - I rewrote the story a bit to help explain what I want to try to do.  

My vision is that there is a command line utility like mlcp or corb, let's call it msb.  And I can pass the host, port, username, and password to this utility along with the job name and the parameters for that job.  

    msb -job LoadDocumentsFromDirectory -properties job.properties

    msb -job LoadDocumentsFromDirectory -host localhost -port 8100 ....

With regards to implementation, I would pass in a DatabaseClient to the ItemWriter (or the ItemReader), but I also need to write the JobRepository data to MarkLogic as well.  And this might be in a different database.  So I need two instances of [DatabaseClientConfig](https://github.com/rjrudin/ml-javaclient-util/blob/master/src/main/java/com/marklogic/client/helper/DatabaseClientConfig.java), one for the MarkLogic JobRepository and one for the target database.  I'm still thinking about the best way to code this up. 

I like the link referenced above as a way to represent properties.

**Comment by rjrudin** [comment]
Documenting what Scott and I discussed today:

- Will use Apache commons-cli to parse command line options
- A "-job" parameter will specify the name of the Spring Bean that corresponds to the Batch Job to execute.
- An optional "-config" parameter will specify the name of the Spring Bean that corresponds to the Config class to use for properties
- Somehow, additional optional parameters will be able to override properties in the Config class (this part may be tricky, I've only used commons-cli to define static command line options)

This should then give us a flexible command line interface for invoking any Job that's on the classpath, with any Config class that's on the classpath.

**Comment by sastafford** [comment]
This is going to need an updated ml-junit and ml-javaclient-util jar (see recent pull requests on those projects).  Right now, the properties are being picked up from src/test/resources/job.properties

**Comment by sastafford** [comment]
@rjrudin I wrote Issue #31 a while back with the vision in mind.  Let's scope this issue to only accept job configuration properties into a job.  Let's keep the command line work to issue #31.

**Comment by sastafford** [comment]
See [JobProperties](https://github.com/sastafford/marklogic-spring-batch/blob/dev/core/src/main/java/com/marklogic/spring/batch/configuration/JobProperties.java)

0b67e797d1ef345b37de137ff0cd50a95f64cd7a
