### ISSUE TITLE
Automatically deploy a MarkLogic JobRepository 

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#63]
As a developer
I want to TITLE
So that I can store job execution metadata into MarkLogic.

One deliverable will be the marklogic-spring-batch.jar file.  It is going to contain the following custom code artifacts
* ItemReaders
* ItemProcessors
* ItemWriters
* MarkLogic Job Library
* Any supporting helper files
* MarkLogicBatchConfiguration
* Data Access Objects for a MarkLogicJobRepository

A second deliverable needs to be created that packages up the configuration to support the back end and application layer for a MarkLogic Spring Batch.  This would be the gradle file, and the ml-config, and ml-modules data.  

Should consider separating the MarkLogic Job library and the MarkLogic Job Repository

**Comment by rjrudin** [comment]
Re: the ml-config stuff - I recommend capturing that as files under src/main/resources that can be accessed via the classpath - I think Spring's ClassPathResource is a good fit here (there's also PathMatchingResourcePatternResolver). 

There's also not really much harm in just hardcoding the files as strings into Java classes too. Then you don't need to fetch anything from the classpath. 

You can then use the Manager classes in ml-app-deployer instead of the Command classes to load things - e.g. DatabaseManager. And modules can always be loaded either via ml-javaclient-util or just via the regular REST API classes.

**Comment by sastafford** [comment]
8520b277bf985a3071509979d55cf94916b993a6

**Comment by rjrudin** [comment]
A note on this - the CLI work I'm doing is making it so that the ML JobRepo can be enabled via a command-line arg. The code that determines that could then also ensure that the given host/port has the JobRepo resources deployed.

**Comment by sastafford** [comment]
Just read that.  I was wondering if I should package a separate single executable jar that would set up the JobRepo?  The jar would call the ml-app-deployer code directly.  OR do I create a zip file with the build.gradle, gradle wrapper, and the ml-config/ml-modules directories?  Then deploy using ml-gradle.

**Comment by sastafford** [comment]
It sounds like our msb job utility command line could be used to deploy a MarkLogic JobRepo.  
   
    msb DeployMarkLogicJobRepo -host host -port port

The JobRepo will need to be it's separate app/db/security, since it has specific range indices and options file.

**Comment by rjrudin** [comment]
The way I have it setup on my branch is that when a user includes "jrPassword", MSB knows that the ML Job Repo (JR) is to be used, and thus it configures a DatabaseClientProvider for that purpose (separate from the "main" DatabaseClientProvider). 

At that point, 1 of 3 things is true:

1. The JR resources exist and need no updating
1. The JR resources exist but need updating (perhaps it's a new version of MSB and the search options need updating)
1. The JR resources do not exist at all

I think MSB can use the Mgmt API to detect which scenario is true. I think 1 and 2 can be handled the same way - just update the modules via the Client API. And 3 will be different but can be handled via the Mgmt API.

I feel what's most likely is 1 and 2. If someone really wants to use the JR, it's probably worth the effort to manually configure the ml-gradle files for the resources themselves. I think 3 above is just a friendly optimization that MSB can provide - i.e. by setting up a new default app server and database for the JR.
