### ISSUE TITLE
Use only one Logging library

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#65]
Some classes inherit the LoggingObject from the ml-java-util library and some use the Spring apache logging.  Need to consolidate to use one library.

**Comment by rjrudin** [comment]
Logback is the way to go, and IIRC, Spring dependencies can be modified to exclude log4j from being downloaded, and thus slf4j will use logback, not log4j.

**Comment by sastafford** [comment]
f2c8482ec2d4cbe2dc0a05dba433693f6cd09a4a
