### ISSUE TITLE
Load triples from a directory

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#68]
As a developer
I want to TITLE
So that I can query them from MarkLogic

Make sure to work from the DEV branch.  I'm going to merge some code where the jobs code will live under $PROJECT_ROOT/jobs/src/main/java.  Create a Job config called LoadTriplesFromDirectoryJob and place under com.marklogic.spring.batch.job.  Then write a corresponding test.  

I recommend renaming ReadAndWriteTripleTest to LoadTriplesFromDirectoryJobTest.

**Comment by sastafford** [comment]
The scope of this task is to convert RdfMigrator to be a job invoked via Main program.  Just like SqlMigrator, RdfMigrator can become a job config that is then invoked via Main.  Can then remove commons-cli from the set of dependencies for core.

**Comment by rjrudin** [comment]
https://github.com/sastafford/marklogic-spring-batch/commit/7740f581e513f976cf9f207fc3c502de0dad770e
