### ISSUE TITLE
Migrate data from RDBMS into JSON written to a filesystem

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#71]
As a developer
I want to TITLE
So that I can migrate data from an existing RDBMS to MarkLogic

# Implementation Notes

I believe all this code would need to reside in the _jobs/_ subproject.  This would be a generic job template.  Once it is matured to the specific use case, it may need to reside in a separate codebase.  

## ItemReader 

-  Execute SQL/XML export from RDBMS
-  look into JdbcCursorItemReader<T>
-  what type of object would encapsulate what is coming out of this ItemReader? 
  - Would you use a POJO or would it be better to use a template (Thymeleaf, Freemarker)?
  - XML String, maybe use a w3c.Document object, or just a string

## ItemProcessor 

- Transform to JSON, 

## ItemWriter 

- Write to a filesystem AND/OR directly to MarkLogic

**Comment by rjrudin** [comment]
Is this now just a matter of adding a processor that takes an XML string (as outputted via a SQL query that returns XML) and then converting it to JSON via something like http://stackoverflow.com/questions/28451370/convert-xml-to-json-with-java ?
