### ISSUE TITLE
Only deploy one app server and database

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#76]
Because MSB is a library, I think it only needs one app server and database, which are then used for running tests. This change would require:

- Changing tests to use BasicConfig instead of BasicTestConfig (the latter is for when you have 2 app servers and databases) - can make a base test class that wires in this config so it only needs to be changed in 1 place
- Remove mlTestRestPort

**Comment by sastafford** [comment]
The ml-gradle plugin has been removed and replaced with two commands

    gradle deployMarkLogicJobRepository

    gradle undeployMarkLogicJobRepository

Reads from gradle.properties.  Significant changes to the LoadDocumentsTest and the CorbTest

**Comment by rjrudin** [comment]
I'm confused - I think ml-gradle is still useful for setting up an app server / database / users to use for testing. The Job Repo is separate from that. I think we should provide a user an option to deploy one (or perhaps better yet, an option to export the necessary config files to the src/main/ml-config directory in their own project), but I don't think we want to run tests against the app server / database created for the Job Repo.

**Comment by rjrudin** [comment]
See PR - https://github.com/sastafford/marklogic-spring-batch/pull/84
