### ISSUE TITLE
Download the MarkLogic Spring Batch test library

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#89]
As a developer
I want to TITLE
So that I can reuse the common classes like AbstractJobTest and JobRepoUtils.

Need to create another library with all the helper classes.

**Comment by rjrudin** [comment]
This should just be a matter of adding a "testJar" task to Gradle - the obi project should have the sample config. May need separate bintray blocks to publish each one - or possibly an if/else block in the Gradle file that determines which bintray block to use, based on a command-line property.

**Comment by sastafford** [comment]
I ended up creating a separate project for the common test code.  I'm restricted to a single bintray block per build.gradle file.  And it was easier to put together another gradle subproject.

**Comment by sastafford** [comment]
418eb67e8fbb40435f62920cc33988e5422ba46e
