### ISSUE TITLE
No longer can execute unit tests within IntelliJ

### ISSUE THREAD

**Issue by sastafford** [sastafford/marklogic-spring-batch#92]
If you try to run a unit test within the core or jobs directory, I'm getting an error message indicating that it cannot find the gradle.properties file or ../core/gradle.properties file based on the spring configuration.

Running _gradle test_ works fine.

**Comment by rjrudin** [comment]
I am guessing Intellij just needs a refresh of the filesystem. Both the core and jobs tests are running fine for me. I'm running them by right-clicking on core/src/test and jobs/src/test and selecting "Run All Tests". 

Make sure that both "core" and "jobs" are defined as "modules" in the project too. I believe that ensure that when a test is run, it's from the module root directory that it belongs to. This should ensure that the "file:../core/gradle.properties" path in JobTestConfig resolves correctly.

**Comment by sastafford** [comment]
Not sure what happened but I deleted all my IntelliJ project files and recreated the project.  That fixed the problem.
