### ISSUE TITLE
Repackage config classes into "config" package

### ISSUE THREAD

**Issue by rjrudin** [sastafford/marklogic-spring-batch#98]
Most of our config classes are currently in a "job" package, but I think they should be in the"config" package instead.

**Comment by sastafford** [comment]
We also have a package called com.marklogic.spring.batch.configuration.  How should we distinguish between core configuration (i.e. JobRepoConfig, OptionsParsing) and job configuration?

**Comment by rjrudin** [comment]
I recommend renaming "configuration" to "config", and the non-Config classes in the current configuration package could go into config.support, which is a Spring sort of thing to do.
